### PR TITLE
add blurb on goals

### PR DESCRIPTION
**Pull request by kweav**
#### What changes are being implemented in this Pull Request?

Add a blurb on goals of DNA sequencing experiments.

Also, enumerated the different types of general sequencing methods and their acronyms in the section directly following

### New Content Checklist

- [x] New content/chapter is in an Rmd file with [this kind of format and headers](https://github.com/jhudsl/OTTR_Template/blob/main/02-chapter_of_course.Rmd).

- [x] [Bookdown successfully re-renders and any new content files have been added to the _bookdown.yml](https://github.com/jhudsl/OTTR_Template/wiki/Publishing-with-Bookdown).

- [x] Spell check runs successfully in [Github actions style-n-check](https://github.com/jhudsl/OTTR_Template/wiki/How-to-set-up-and-customize-GitHub-actions-robots#spell-check)).

### CODE REVIEW

**Comment by kweav** [comment]
additional commits added a comma in the book.bib and went through 

> ⚠️ broken url errors ⚠️ There are broken url errors that need to be addressed. Click here ➡️ [for broken url errors!](https://github.com/fhdsl/Choosing_Genomics_Tools/blob/preview-54/check_reports/url_checks.tsv) ❗ Add errors that aren't errors to the [resources/ignore-urls.txt](https://github.com/fhdsl/Choosing_Genomics_Tools/edit/DNA_seq_goals/) file of this repo. If you are having troubles see [this guide](https://www.ottrproject.org/faqs.html#Most_Common_Errors) _Comment updated at 2024-05-14-03:06:45 with changes from [a8e7034](https://github.com/fhdsl/Choosing_Genomics_Tools/commit/a8e70342b0bb601859c2fc21e000c827c22f4ca1)_

Not sure what's up with this broken link. It was fine when I tried it, and it hasn't been flagged in any of the previous check reports this evening.

**Comment by kweav** [comment]
I had a few references where I didn't type the reference `[@ReferenceName]` correctly, so I corrected those and others flagged with a warning during the render preview. Those were a couple of the last few commits.

**Comment by cansavvy** [comment]
> additional commits added a comma in the book.bib and went through
> 
> > ⚠️ broken url errors ⚠️ There are broken url errors that need to be addressed. Click here ➡️ [for broken url errors!](https://github.com/fhdsl/Choosing_Genomics_Tools/blob/preview-54/check_reports/url_checks.tsv) ❗ Add errors that aren't errors to the [resources/ignore-urls.txt](https://github.com/fhdsl/Choosing_Genomics_Tools/edit/DNA_seq_goals/) file of this repo. If you are having troubles see [this guide](https://www.ottrproject.org/faqs.html#Most_Common_Errors) _Comment updated at 2024-05-14-03:06:45 with changes from [a8e7034](https://github.com/fhdsl/Choosing_Genomics_Tools/commit/a8e70342b0bb601859c2fc21e000c827c22f4ca1)_
> 
> Not sure what's up with this broken link. It was fine when I tried it, and it hasn't been flagged in any of the previous check reports this evening.



> additional commits added a comma in the book.bib and went through
> 
> > ⚠️ broken url errors ⚠️ There are broken url errors that need to be addressed. Click here ➡️ [for broken url errors!](https://github.com/fhdsl/Choosing_Genomics_Tools/blob/preview-54/check_reports/url_checks.tsv) ❗ Add errors that aren't errors to the [resources/ignore-urls.txt](https://github.com/fhdsl/Choosing_Genomics_Tools/edit/DNA_seq_goals/) file of this repo. If you are having troubles see [this guide](https://www.ottrproject.org/faqs.html#Most_Common_Errors) _Comment updated at 2024-05-14-03:06:45 with changes from [a8e7034](https://github.com/fhdsl/Choosing_Genomics_Tools/commit/a8e70342b0bb601859c2fc21e000c827c22f4ca1)_
> 
> Not sure what's up with this broken link. It was fine when I tried it, and it hasn't been flagged in any of the previous check reports this evening.

Now its a different URL that's coming up as broken. But it works when I try it so I'm going to not worry about it for this PR but we have an issue to track this and can revisit it later #55

**Review by cansavvy — APPROVED** [review]
Thanks for these fixes! Great work @kweav !

**Pull request merged**
